<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<meta charset="utf-8">
		
		
        <title>Heroes of Uppsala</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="HoU.css">
    </head>
    <body>
		<div id="nav">    
            <div class="section group">
                <div class="col span_3_of_3">
                    <ul> <?php
						if(isset($_SESSION['user_email']))
						{ ?>
                        <li><a href="index.php">START</a></li>
						<!-- <li><a href="login.php">LOG IN</a></li>-->
                        <li><a href="logout.php">LOG OUT</a></li>
						<!-- <li><a href="register.php">REGISTER</a></li>-->
                        <li><a href="profile.php">PROFILE</a></li>
                        <li><a href="missions.php">MISSIONS</a></li>
                        <li><a href="about.php">ABOUT</a></li>
                        <li><a href="contact.php">CONTACT</a></li>
						<?php }
						else 
						{ ?>
						<li><a href="index.php">START</a></li>
						<li><a href="login.php">LOG IN</a></li>
                        <!-- <li><a href="logout.php">LOG OUT</a></li>-->
						<li><a href="register.php">REGISTER</a></li>
                        <!--<li><a href="profile.php">PROFILE</a></li>-->
                        <li><a href="missions.php">MISSIONS</a></li>
                        <li><a href="about.php">ABOUT</a></li>
                        <li><a href="contact.php">CONTACT</a></li>
						<?php } ?>

                    </ul>
                </div>
            </div>
        </div>  

		
        <div class="section group">
            <!--<div class="col span_1_of_3" id="leftnav">
                <img src="heroesofuppsala.png" alt="Heroes of Uppsala">
            </div>-->
            <div class="col span_2_of_3" id="content">
                
                
                <div class="section group">
                    <div class="login_forms" id="content">
                        <h1>Register</h1>
						<form method="POST" action="register-process.php" onsubmit="return validateInput()">

							<input name="email" id="email" type="text" placeholder="E-Mail">
							<input name="password" id="password" type="password" placeholder="Password">
							<input name="password2" id="password2" type="password" placeholder="Password">
							<input id="login_button" type="submit" value="Register">
							<label for="agree">I agree with the Terms and Conditions</label>
							<input type="radio" id="agree" name="yes" value="yes">
							<p>The Nonprofit Organizations as well as the Volunteers are both referred to as User. Nonprofit Organizations are referred to as NO and Volunteers are referred to as Applicant. Heroes of Uppsala are referred to as HoU. </p>
							<p> 1.1 General </p>
							<p>Both NO and Heroes are obliged to follow the Terms and Conditions after creating an account. If the Terms and Conditions change, these modifications will be posted on the homepage of HoU and the User is obliged to follow these.</p>
							<p>Swedish law applies since HoU is based in Sweden. </p>
							<p> 1.2 Immaterial Rights </p>
							<p>All material created by HoU is published according to Creative Commons (CC BY 4.0). All content generades by the User is the User’s to answer for.</p>
							<p> 1.3 Messaging Service</p>
							<p> The content in the Messaging Service has to be characterized by politeness and decency.</p>
							<p> 1.4 Responsibility</p>
							<p> The User is always responsible for all content generated by the User. The NO chooses, based on its own interest, which Applicant is suitable for the mission. Eventual disputes are to be externally solved between NO and Applicant.</p>
							<p> HoU is not responsible if either the NO or the Applicant in some way not complete anything determined.</p>
							<p> By applying for a mission the Applicant accepts to complete the mission, and by approving the Applicant the NO accepts to let the Applicant do so.</p>
							<p> The User is responsible of keeping the User’s personal data updated and correct.</p>
							<p> 1.5 Personal Data</p>
							<p> HoU requires some personal data to be able to provide the e-Service. HoU processes it according to Swedish law.</p>
							<p> All personal data are saved as long as the User has an active account at HoU. An account is classified as active until the User deletes it, or if it has been non-active during xx months.</p>
							<p> 1.6 Contact </p>
							<p> Heroes of Uppsala AB, Ekonomikum, Uppsala.</p>
							
						</form>

                    </div>
                </div>    

                
            </div>
        </div>
			<script src="register.js"> </script>
    </body>
</html>